version: '2'
services:
  message-server:
    container_name: spring-jwt
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-jwt:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge